import BaseDataScript from 'src/common/adapters/BaseDataAdapter/scripts';
import { SqlAction, SqluiCore } from 'typings';
export declare function getAllImplementations(): BaseDataScript[];
export declare function getConnectionFormInputs(dialect?: string): string[][];
export declare function consolidateDialects(res: string[], script: BaseDataScript): string[];
export declare const SUPPORTED_DIALECTS: string[];
export declare const DIALECTS_SUPPORTING_MIGRATION: string[];
export declare const DIALECTS_SUPPORTING_CREATE_FORM: string[];
export declare const DIALECTS_SUPPORTING_EDIT_FORM: string[];
export declare function isDialectSupportMigration(dialect?: string): boolean;
export declare function isDialectSupportCreateRecordForm(dialect?: string): boolean;
export declare function isDialectSupportEditRecordForm(dialect?: string): boolean;
export declare function isDialectSupportVisualization(dialect?: string): boolean;
export declare function getSyntaxModeByDialect(dialect?: string): string;
export declare function getIsTableIdRequiredForQueryByDialect(dialect?: string): boolean;
export declare function getDialectTypeFromConnectionString(connection: string): string;
export declare function getDialectType(connection: string): SqluiCore.Dialect;
export declare function getDialectName(dialect?: string): string;
export declare function getDialectIcon(dialect?: string): string;
export declare function getSampleConnectionString(dialect?: string): string;
export declare function getSampleSelectQuery(actionInput: SqlAction.TableInput): string;
export declare function getTableActions(actionInput: SqlAction.TableInput): SqlAction.Output[];
export declare function getDatabaseActions(actionInput: SqlAction.DatabaseInput): SqlAction.Output[];
export declare function getConnectionActions(actionInput: SqlAction.ConnectionInput): SqlAction.Output[];
export declare function getCodeSnippet(connection: SqluiCore.ConnectionProps, query: SqluiCore.ConnectionQuery, language: SqluiCore.LanguageMode): string;
