name: Main - Release

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Release notes"
      node_version:
        description: "Node.js version"
        default: "24"

permissions:
  contents: write
  pages: write
  id-token: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  package:
    uses: ./.github/workflows/package.yml
    with:
      node_version: ${{ inputs.node_version }}
      release_mode: "production"
      run_format: false
      release_notes: ${{ inputs.message }}
    secrets: inherit
