name: package-electron

on:
  workflow_dispatch:
    inputs:
      message:

jobs:
  create_release:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    outputs:
      package_version: ${{ steps.package-version.outputs.current-version }}
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      # get the latest package version
      - uses: actions/checkout@v2
      - id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: '.'

      # Create a release
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          release_name: ${{ steps.package-version.outputs.current-version }}
          body: |
            Release Notes:
            ${{ github.event.inputs.message }}
          draft: false
          prerelease: true

  build_windows:
    needs: [create_release]
    runs-on: [self-hosted, windows]
    timeout-minutes: 12
    steps:
      # build
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run dist
      - run: mv ./dist/sqlui-native*.exe ./dist/sqlui-native.exe

      #  Upload binary step
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_upload_url }}
          asset_path: ./dist/sqlui-native.exe
          asset_name: sqlui-native-${{ needs.create_release.outputs.package_version }}.exe
          asset_content_type: application/octet-stream

  build_macos:
    needs: [create_release]
    runs-on: [self-hosted, macos]
    timeout-minutes: 12
    steps:
      # build
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run dist
      - run: mv ./dist/sqlui-native*.dmg ./dist/sqlui-native.dmg

      #  Upload binary step
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_upload_url }}
          asset_path: ./dist/sqlui-native.dmg
          asset_name: sqlui-native-${{ needs.create_release.outputs.package_version }}.dmg
          asset_content_type: application/octet-stream

  publish:
    needs: [create_release, build_windows, build_macos]
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: echo " ${{ needs.create_release.outputs.package_version }}"
      - run: |
          sed -i "s/app_version:.*\+/app_version: ${{ needs.create_release.outputs.package_version }}/" _config.yml
      - uses: EndBug/add-and-commit@v8
        with:
          message: 'CI / CD - New Release ${{needs.create_release.outputs.package_version}}'
