name: pr-package-electron

on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run dist
